### ISSUE TITLE
Overview -> Barriers -> Reason column isn't visible

### ISSUE THREAD

**Issue by Trider12** [GPUOpen-Tools/radeon_gpu_profiler#103]
I'm using RGP 2.2.0.16 on Windows 11 and a 1920x1080 monitor with Windows display scale set to 100% (the default value).
The `Reason` column of the `Barriers` table doesn't fit into the view.
The horizontal scrollbar is at its right-most position. Other columns have enough free horizontal space to make the last column fit.

![image](https://github.com/user-attachments/assets/e92cfbd2-b56e-4b16-9612-f385ee421770)

**Comment by chesik-amd** [comment]
This issue should be resolved in the RGP v2.3 release
