### ISSUE TITLE
Window cannot be resized, it's fixed and exceeded monitor's resolution

### ISSUE THREAD

**Issue by haxpor** [GPUOpen-Tools/radeon_gpu_profiler#37]
I'm using v. 1.7.0.29 (latest downloaded on release tab) on Ubuntu 19.10, kernel 5.3.18-050318-generic.

The window of RGP Profiler cannot be resized, and it exceeds my monitor's resolution so I cannot see the whole thing. My monitor resolution is 1366x768 pixels. Does RGP Profiler require at least larger resolution than mine ? Thanks!

**Comment by chesik-amd** [comment]
Current versions of RGP should behave much better at lower resolutions. We do recommend a minimum resolution of 1920x1080. Lower resolutions, while usable, may not offer the best user experience.
