### ISSUE TITLE
RX5600XT support 

### ISSUE THREAD

**Issue by pmathia0** [GPUOpen-Tools/radeon_gpu_profiler#39]
Could you please add support for RX5600XT. It seems to work but after a while it shows a dialog unsupported device and I can't use the profiler anymore without pc reboot

**Comment by chesik-amd** [comment]
Can you check if you still see problems with the RGP 1.8 version that was released yesterday?

**Comment by pmathia0** [comment]
Seems to be fixed now. So maybe documentation/supported devices should be updated?

**Comment by chesik-amd** [comment]
Documentation has been updated.  Thanks for letting us know about this
