### ISSUE TITLE
Connection dilemma

### ISSUE THREAD

**Issue by gggh000** [GPUOpen-Tools/radeon_gpu_profiler#40]
I have difficulty with launching RadeonDeveloperPanel executable from linux ssh terminal.
It complains it can not access x window
./RadeonDeveloperPanel
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

But connection settings to same ssh session already setup X-11 forwarding enabled. Why?

I also tried remotely from invoking RadeonDeveloperPanel from client Windows machine and establish connection to ssh connected machine through its IP.
But when remotely connecting this way, when I try select the app to dump the rgp trace, it allows me to browse through files on the client machine not the ssh machine in which the ./RadeonDeveloperServiceCli is running and also it is the same machine in which I am going to run the target machine. 
How can browse its folder and files from remotely connected client?

**Comment by chesik-amd** [comment]
To capture a profile on a headless remote machine, you are on the right track.

First run RadeonDeveloperServiceCLI on the machine.  Then run RadeonDeveloperPanel (RDP) on a local machine.  In RDP, establish a connection to the remote machine (via either host name or IP address).

Assuming you are using RGP 1.8, the simplest thin to do would be to make sure "Advanced mode" is disabled on the "My applications" tab of the "System" tab.

Then when you start a Vulkan or OpenCL application on the remote machine, RDP on the local machine should switch over to the Applications tab and show the name of the executable, the API, and the process id.

You should then be able to capture a profile from the application running on the remote system

**Comment by chesik-amd** [comment]
Closing issue.  Please let us know if you still have issues with remote connections
