### ISSUE TITLE
Theoretical occupancy does not take RDNA wave64 into account

### ISSUE THREAD

**Issue by ishitatsuyuki** [GPUOpen-Tools/radeon_gpu_profiler#52]
I was long wondering why my compute shader had a mediocre occupancy even though it was showing "running maximum wavefronts for your ASIC".

![image](https://user-images.githubusercontent.com/12389383/112259885-631c6180-8cac-11eb-90d7-eb16e6444b6d.png)

Well, through some testing, it turned out that when running with wave64, the hardware can run up to the equivalent of 40 wavefronts in wave32. So the calculation of theoretical occupancy needs to take that into account. Please fix this by ~~bumping the maximum theoretical occupancy~~ halving the hardware register count in wave64 mode accordingly.

**Comment by ishitatsuyuki** [comment]
Environment is Mesa RADV master, I'm aware that profiling with RADV is experimental so please let me know if it should be fixed Mesa side (e.g. by writing doubled register usage to the trace).

**Comment by Venemo** [comment]
CC @hakzsam - perhaps he can help with this on the RADV side.

**Comment by ishitatsuyuki** [comment]
Looks like this was already resolved on the RADV side.
