### ISSUE TITLE
Fails to open rgp capture file

### ISSUE THREAD

**Issue by masahi** [GPUOpen-Tools/radeon_gpu_profiler#58]
The same issue with https://github.com/GPUOpen-Tools/radeon_gpu_profiler/issues/26. The file is attached.
[iree-run-module-vulkan-gui-20211105-130132.zip](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/files/7480501/iree-run-module-vulkan-gui-20211105-130132.zip)

The application runs a dummy render loop and runs a deep learning model inference in each frame. More details in https://github.com/google/iree/blob/main/docs/developers/developing_iree/profiling_vulkan_gpu.md#desktop-gpus

System info:
OS: Ubuntu 20.04
RGP: 1.11
GPU: Vega 8 APU
Driver: AMDVLK (don't know how to read the version)

**Comment by chesik-amd** [comment]
Hi.  I am able to open the .[rgp file you provided](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/files/7480501/iree-run-module-vulkan-gui-20211105-130132.zip) using [RGP 1.11](https://gpuopen.com/download/radeon-developer-tool-suite/RadeonDeveloperToolSuite-2021-06-30-819.tgz)

I also tried the Windows build of RGP and it can open the .rgp file just fine too.  Did you attach the correct .rgp file? If you can provide an .rgp file that fails to load, we will take a look.  Thanks.

**Comment by masahi** [comment]
I see. When I opened this issue, I got an error below.

![Uploading Screenshot from 2020-11-17 10-17-11.png…]()

I have a feeling that the failure is due to the fact that the profiler stores `rgp` file under a path that contains non-English character. The `rgp` file is stored in my /home/masa/ドキュメント/rgp_profiles/iree-run-module-vulkan-gui directory, where "ドキュメント" is the Japanese word for "Document". If I move the same file to /home/masa, then RGP can open this file.

Does this sound a bell?

**Comment by chesik-amd** [comment]
Hi, yes, there are some problems in current builds when opening .rgp files in paths with Unicode characters. We will investigate and hope to be able to provide a fix in a future release.

**Comment by chesik-amd** [comment]
This issue should be resolved in current RGP builds. If you still encounter problems, please let use know
