### ISSUE TITLE
Instruction hit count is same within kernel asm?

### ISSUE THREAD

**Issue by hgtsoi** [GPUOpen-Tools/radeon_gpu_profiler#62]
How the RGP profiles instruction hit count? 
All the assembly code lines got the same hit count. The num of hit count might vary for different kernels.
Does it mean how many times the whole kernel being executed? Or it just equals to that then.

**Comment by chesik-amd** [comment]
Closing this issue, and there doesn't seem to be a bug here. If I am mistaken and you are seeing a bug, please reopen with more details and a test case. Thanks!
