### ISSUE TITLE
Indistingushable blue tones in palette and unchangable color for API PSO color keys

### ISSUE THREAD

**Issue by ishitatsuyuki** [GPUOpen-Tools/radeon_gpu_profiler#64]
The following two blue tones are visually indistinguishable.

![image](https://user-images.githubusercontent.com/12389383/161569227-e34875ef-3bc0-4f51-90fa-d6bdd5657e61.png)

I've changed one of them to #0011a9 in settings, but that doesn't apply to API PSO coloring.

Please review your default color palette and also make customizations apply to API PSO coloring.

**Comment by chesik-amd** [comment]
RGP 1.13.1 allows you to modify the random seed used in coloring modes that generate random colors (like the Color by API PSO mode).  This is available in the Settings UI
