### ISSUE TITLE
RGP can't sort barriers by duration or drain time

### ISSUE THREAD

**Issue by Venemo** [GPUOpen-Tools/radeon_gpu_profiler#67]
RGP capture to reproduce this issue: https://drive.google.com/file/d/1__36B-xPCSjanNHQcZVjsVR7Kr2hn9fN/view -> `GWT-20220429-171209-windows-scene-2.rgp`

# Steps to reproduce:

1. Launch RGP
2. Open `GWT-20220429-171209-windows-scene-2.rgp`
3. Go to Overview -> Barriers
4. Click on the "Duration" column to try to sort the barrier eventy by their duration

## Expected result:

Events are sorted by duration

## Actual result:

Events are not sorted by their duration

# Screenshot:

![Screenshot from 2022-05-02 13-04-25](https://user-images.githubusercontent.com/722813/166224385-c9309597-1c05-4225-9736-7490690d4c0c.png)

**Comment by chesik-amd** [comment]
This has been fixed in RGP 1.13.1
