### ISSUE TITLE
RGP can't display D3D12 front-face stencil func value

### ISSUE THREAD

**Issue by Venemo** [GPUOpen-Tools/radeon_gpu_profiler#68]
RGP capture to reproduce this issue: https://drive.google.com/file/d/1__36B-xPCSjanNHQcZVjsVR7Kr2hn9fN/view -> `GWT-20220429-171209-windows-scene-2.rgp`

# Steps to reproduce:

1. Launch RGP
2. Open `GWT-20220429-171209-windows-scene-2.rgp`
3. Go to Pipeline state
4. Find event 4983
5. Click "OM"
6. Look at the Front face stencil func

## Expected result:

See a valid enumeration value for the stencil func.

## Actual result:

RGP prints `{0}` --- unclear what this means.

# Screenshot:

![Screenshot from 2022-05-02 13-08-18](https://user-images.githubusercontent.com/722813/166224742-d23b6636-3824-4071-9b03-7a7e465e6df3.png)

**Comment by chesik-amd** [comment]
This has been fixed in RGP 1.13.1
