### ISSUE TITLE
Missing Vulkan front and back stencil reference in context rolls view

### ISSUE THREAD

**Issue by Venemo** [GPUOpen-Tools/radeon_gpu_profiler#69]
Reproducible with any Vulkan RGP capture.

# Steps to reproduce

1. Open RGP
2. Open a Vulkan capture
3. Go to Overview -> Context rolls
4. Find "VkPipelineDepthStencilState"

## Expected result

There should be rows for the front and back stencil reference, see [the Vulkan docs](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkStencilOpState.html).

Note that the reference is controlled by the same HW register as the compare and write masks.

## Actual result

Stencil reference is missing.

# Screenshot

![Screenshot from 2022-05-02 13-11-51](https://user-images.githubusercontent.com/722813/166225221-5fa3debe-eb14-4930-b802-6e2913fa0dc0.png)

**Comment by chesik-amd** [comment]
This has been addressed in RGP 1.13.1
