### ISSUE TITLE
"RadeonDeveloperToolSuite-2022-06-10-45.tgz" file is broken..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Tools/radeon_gpu_profiler#71]
Hi,
can reupload a working one please?
thanks..

**Comment by chesik-amd** [comment]
Hi.

Thanks for reporting this.

What exact issues are you seeing with the .tgz file?  Our QA team was just able to download it and extract it without any issues. I quickly tested on a Linux system, and the contents seem to extract ok for me as well.  I used this command:  " tar zxfv RadeonDeveloperToolSuite-2022-06-10-45.tgz" 

Thanks,
Chris

**Comment by oscarbg** [comment]
Hi,
thanks!
today it works.. sorry if my fault, but promise you when reported few days ago was broken.. tried downloading multiple times and used similar tar -xvf as today..

**Comment by chesik-amd** [comment]
Glad it's working now.  And thanks for taking the time to report this to us.

**Comment by newincpp** [comment]
Hi, I'm having the same issue with all tgz in 2023:
```
newin@vega Downloads % tar xvzf RadeonDeveloperToolSuite-2023-02-15-1051.tgz 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
newin@vega Downloads % tar xvzf RadeonDeveloperToolSuite-2023-04-25-1075.tgz 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
newin@vega Downloads % tar xvzf RadeonDeveloperToolSuite-2023-05-22-1083.tgz 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by chesik-amd** [comment]
How are you downloading the archives?  I just tried the following and it works for me:

 wget https://gpuopen.com/download/radeon-developer-tool-suite/RadeonDeveloperToolSuite-2023-05-22-1083.tgz
 tar zxfv RadeonDeveloperToolSuite-2023-05-22-1083.tgz

**Comment by newincpp** [comment]
sorry I had desktop issues for a couple of month.
Both from the website https://gpuopen.com/rga/ and the release page give me same error.
But (surprisingly) your wget works. Since my previous post there was a couple of update so the link wasn't really usefull anymore but I was able to guess the link I would need to get the latest version. And the wget again worked while the one from both the website and the archive didn't. It's really strange.
