### ISSUE TITLE
Total thread groups number formatting in Pipeline State view can be misleading

### ISSUE THREAD

**Issue by luckyxxl** [GPUOpen-Tools/radeon_gpu_profiler#72]
The dimension separator of multidimensional numeric values looks the very same as the thousands-separator of single numbers in the Pipeline State view. This can be confusing in certain scenarios.

Please consider the following example:

![grafik](https://user-images.githubusercontent.com/10104068/186642454-3d710f1f-3651-40c8-a768-b3474a7c0f45.png)

In the pipeline state of a dispatch with size (1, 240, 129), the total "Thread groups count" number (orange) looks the same as the "Total threads" number (blue), yet one is a three-dimensional value while the other is a one dimensional one. This leads one to misinterpret the "Thread groups count" as a one-dimensional number as well, so 1240129, which doesn't make sense.

Maybe consider adding a space after the comma when separating dimensions like in the event tree on the left?

**Comment by chesik-amd** [comment]
This has been addressed in RGP v1.14
