### ISSUE TITLE
'Raytracing capture is not supported for this system configuration' on Windows 11 with a AMD 6900XT

### ISSUE THREAD

**Issue by expenses** [GPUOpen-Tools/radeon_gpu_profiler#74]
Hi, I'm getting this on a system that can do profiles and memory traces perfectly file. What do I need to do to get this to work?

**Comment by chesik-amd** [comment]
This sounds like an RRA capture issue (not an RGP issue).  Can you report this in the RRA repo? Folks there should be able to help

https://github.com/GPUOpen-Tools/radeon_raytracing_analyzer/issues
