### ISSUE TITLE
Crash loading profile

### ISSUE THREAD

**Issue by bdenhollander** [GPUOpen-Tools/radeon_gpu_profiler#81]
Attempting to open the attached .rgp crashes GPU Profiler V1.14.0.10 on Windows 10. The profile was captured during OpenMM's amoebagk benchmark while attempting to catch an elusive instance of a kernel named `computeGKForces`.

[python-20230121-114412.zip](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/files/10472609/python-20230121-114412.zip)

**Comment by chesik-amd** [comment]
The crash issue should be resolved in the 1.14.1 patch release that was published today.
