### ISSUE TITLE
Question about wavefront occupancy in rgp.

### ISSUE THREAD

**Issue by zouwen4321** [GPUOpen-Tools/radeon_gpu_profiler#86]
why device configuration show wavefronts per SIMD is 16 that data of rgp collected on AMD W6800? The RDNA white paper said each SIMD have 20 wavefront entries in RDNA frontend. Is this the same conception?

**Comment by chesik-amd** [comment]
20 is correct for first generation RDNA GPUs (i.e. RX 5000 series).  For RDNA2 (RX 6000 series), the correct number is 16.
