### ISSUE TITLE
Unreadable white text on white background in KDE Plasma 5 with breeze-dark theme

### ISSUE THREAD

**Issue by Firestar99** [GPUOpen-Tools/radeon_gpu_profiler#88]
I'm running Ubuntu 23.04 with the KDE Plasma 5 Desktop with the "breeze-dark" theme. If I start RGP (or any other of your utilities) a lot of text is white on white background making it unreadable. Here an example of the RGP Device Configuration page:
![image](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/assets/31222740/f2daa25a-9436-4db6-ac1b-891efac825c5)

If I switch my desktop theme to the light theme "breeze" (without dark) it works just fine:
![image](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/assets/31222740/5fa4244b-b1d3-4566-86c0-4b118f39eb43)

But I can't seem to find a way to force light mode on the application without switching my entire desktop over to light mode. I've attempted to use qt5ct to override the QPA theme to a light one but it didn't work on RGP:
1. `apt install qt5ct`
2. run `qt5ct` and configure it to some light theme
3. `QT_QPA_PLATFORMTHEME=qt5ct ./RadeonGPUProfiler` and observe no change in theme for RGP, but on other applications launched like that.

Any other idea on how to force RGP to light theme would be appreciated :D

**Comment by chesik-amd** [comment]
Current builds of RGP do not properly support Dark themes.  We are planning to improve this in future RGP releases

**Comment by Firestar99** [comment]
I specifically created a separate issue as I **don't** want a dark mode. I just want to be able to force it to use light mode, without having to switch my entire desktop to light mode.

**Comment by chesik-amd** [comment]
Understood.  Part of the improvement plans I mentioned include allowing a light or dark theme in RGP independent of the current OS theme.

**Comment by chesik-amd** [comment]
This should be fixed in RGP 1.16 (released last week).  Please let us know if you still see issues with this setup.

**Comment by Firestar99** [comment]
Works perfectly, thanks! :smile:
