### ISSUE TITLE
RDP Will not capture a profile from a program

### ISSUE THREAD

**Issue by nlbutts** [GPUOpen-Tools/radeon_gpu_profiler#94]
RDP bug report
==========================================
Description
I am trying to profile any of the hipblas examples. Specifically hipblas-example-sgemm. I followed the directions here
https://radeon-developer-panel.readthedocs.io/en/latest/#how-to-profile-your-application

I had to use the Advanced Mode to add the program. But when I run the program it doesn't capture. Nor can I select the Capture Profile button. As it is grayed out.

![image](https://github.com/GPUOpen-Tools/radeon_gpu_profiler/assets/16577535/028b621e-6560-4c23-a839-6db393216e76)

==========================================
Steps to Reproduce
1. Follow the instructions
2. Compile the hipblas code
3. Run hipblas-example-sgemm

==========================================
Host System Information

RDP Version: Radeon Developer Panel v2.12.0.20
RDP build Date: 12/04/2023

Operating System: Ubuntu 22.04.3 LTS
Qt Version: 5.15.2

Tool Version: 2.1.0
Router Version 0.13.0

==========================================
Connected System Information

Driver Version: 23.0.4-0ubuntu1~22.04.1
GPUOpen Interface Major Version: 42

Operating System Name: Ubuntu 22.04.3 LTS
Operating System Description: Linux 6.2.0-37-generic x86_64     #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2

GPUs:
******************************************
Name: AMD Radeon RX 7800 XT

ASIC info
************
Device Id: 29822
Revision: 200
Family: 145
gfx_engine: 0

**Comment by bdenhollander** [comment]
Only [Vulkan profiling](https://radeon-developer-panel.readthedocs.io/en/latest/#graphics-apis-rdna-hardware-and-operating-systems) is possible with Ubuntu in Radeon GPU Profiler. HIP and OpenCL profiling are possible on Windows. You can use [rocprof](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/profiler_home_page.html) instead.

**Comment by chesik-amd** [comment]
@bdenhollander is correct. HIP profiling on Linux (where the underlying driver stack is ROCm) is not supported by RDP/RGP.
